#!/usr/bin/env python3
"""Compile native macOS 26+ icon appearances with Xcode 26+.

The catalog is checked in so normal builds, including older Xcode CI hosts,
do not need Icon Composer. Legacy ICNS is generated by gen-icons.ps1.
"""

import hashlib
import json
from pathlib import Path
import subprocess
import tempfile
import xml.etree.ElementTree as ET


def main():
    root = Path(__file__).resolve().parent
    icons = root / "icons"
    document = icons / "Wisp.icon"
    ET.register_namespace("", "http://www.w3.org/2000/svg")
    for source, target in [
        ("app-icon.svg", "wisp-light.svg"),
        ("app-icon-dark.svg", "wisp-dark.svg"),
    ]:
        svg = ET.parse(icons / source).getroot()
        svg.remove(svg.find("{http://www.w3.org/2000/svg}rect"))
        ET.indent(svg, space="  ")
        (document / "Assets" / target).write_text(
            ET.tostring(svg, encoding="unicode") + "\n", encoding="utf-8"
        )

    with tempfile.TemporaryDirectory(prefix="wisp-native-icon-") as output:
        output = Path(output)
        subprocess.run(
            [
                "xcrun", "actool", str(document), "--compile", str(output),
                "--platform", "macosx", "--target-device", "mac",
                "--minimum-deployment-target", "10.13", "--app-icon", "Wisp",
                "--output-partial-info-plist", str(output / "partial.plist"),
                "--output-format", "human-readable-text", "--warnings", "--errors",
                "--notices", "--lightweight-asset-runtime-mode", "enabled",
            ],
            check=True,
        )
        catalog = output / "Assets.car"
        records = json.loads(subprocess.check_output(
            ["xcrun", "assetutil", "--info", str(catalog)], text=True
        ))
        appearances = sorted({
            item["Appearance"] for item in records
            if item.get("AssetType") == "IconImageStack" and item.get("Name") == "Wisp"
        })
        required = {"NSAppearanceNameAqua", "NSAppearanceNameDarkAqua"}
        if not required.issubset(appearances):
            raise RuntimeError(f"Missing native icon appearances: {appearances}")
        (icons / "Assets.car").write_bytes(catalog.read_bytes())

    paths = [
        Path(__file__).resolve(), icons / "app-icon.svg", icons / "app-icon-dark.svg",
        document / "icon.json", *sorted((document / "Assets").glob("*.svg")),
        icons / "Assets.car",
    ]
    provenance = {
        "toolchain": subprocess.check_output(["xcodebuild", "-version"], text=True).strip(),
        "appearances": appearances,
        "sha256": {
            path.relative_to(root).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in paths
        },
    }
    (icons / "macos-icon-build.json").write_text(
        json.dumps(provenance, indent=2) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
