"""Single source of truth for DepMap natural-language intent capabilities."""

from typing import Any

INTENT_CAPABILITIES: tuple[dict[str, Any], ...] = (
    {
        "intent": "provider_status",
        "description": "Check the configured DepMap release, QA state, installed modules, and evidence boundary.",
        "required": [], "optional": [],
        "examples_zh": ["DepMap服务器正常吗", "当前是什么数据版本"],
        "precise_prompt_template_zh": "检查当前DepMap远程知识服务的版本与状态。",
        "confusable_with": ["analysis_inventory"], "mcp_tool": "depmap_status",
    },
    {
        "intent": "lineage_resolution",
        "description": "Resolve a user cancer term to a canonical DepMap lineage before querying lineage evidence.",
        "required": ["cancer_term"], "optional": ["candidate_lineages"],
        "examples_zh": ["结直肠癌在DepMap里对应哪个癌种", "白血病属于哪个lineage"],
        "precise_prompt_template_zh": "把{cancer_term}解析成DepMap标准lineage；歧义时返回候选。",
        "confusable_with": ["cancer_inventory"], "mcp_tool": "depmap_resolve_lineage",
    },
    {
        "intent": "cancer_inventory",
        "description": "List completed evidence families available for one resolved cancer lineage.",
        "required": ["lineage"], "optional": [],
        "examples_zh": ["肝癌有哪些现成分析", "肺癌目前有什么数据"],
        "precise_prompt_template_zh": "列出{lineage}已有的预计算证据类型。",
        "confusable_with": ["analysis_inventory", "cancer_direction_discovery"], "mcp_tool": "depmap_lineage_catalog",
    },
    {
        "intent": "cancer_direction_discovery",
        "description": "Discover bounded precomputed research-direction candidates for one cancer without inventing a gene.",
        "required": ["lineage"], "optional": ["limit"],
        "examples_zh": ["肝癌可以做哪些研究方向", "没有指定基因先给我肺癌候选方向"],
        "precise_prompt_template_zh": "从{lineage}已完成结果发现研究方向，不自行指定锚点。",
        "confusable_with": ["cancer_inventory", "mutation_anchor_discovery"], "mcp_tool": "depmap_lineage_direction_discovery",
    },
    {
        "intent": "analysis_inventory",
        "description": "List completed DepMap analysis units from the unified server directory index without scanning result directories.",
        "required": [],
        "optional": ["module", "limit"],
        "examples_zh": ["服务器完成了哪些分析", "列出突变模块的完成项目", "查看DepMap分析目录"],
        "precise_prompt_template_zh": "从统一目录索引列出已完成的DepMap分析，可选限定模块。",
        "confusable_with": ["cancer_inventory"],
        "mcp_tool": "depmap_analysis_catalog",
    },
    {
        "intent": "mutation_anchor_discovery",
        "description": "Find eligible mutation anchor genes inside one cancer lineage.",
        "required": ["lineage"],
        "optional": ["gene", "event", "limit"],
        "examples_zh": ["肺癌有哪些突变基因可以选", "在结肠癌里选突变锚点", "PTK7在肝癌里能不能当突变锚点"],
        "precise_prompt_template_zh": "在{lineage}中查询{gene}的{event}突变锚点资格，或列出可作为后续依赖分析锚点的突变基因，并返回样本数与每一项门槛的通过/失败原因。",
        "confusable_with": ["mutation_to_dependency"],
        "mcp_tool": "depmap_mutation_anchor_evidence",
        "inventory_patterns": ["*癌种内突变锚定基因选择*"],
    },
    {
        "intent": "mutation_to_dependency",
        "description": "Fix a mutated source gene and rank associated CRISPR dependency targets.",
        "required": ["source_gene"],
        "optional": ["lineage", "event", "target_gene", "limit"],
        "examples_zh": ["TP53突变后依赖哪些基因", "固定KRAS突变看脆弱性", "肝癌PTK7突变后敲除哪个基因效应最大"],
        "precise_prompt_template_zh": "在{lineage}范围内固定{source_gene}的{event}突变，查询相关的CRISPR dependency靶基因；无癌种时使用泛癌观察性合成致死目录。",
        "confusable_with": ["dependency_to_mutation"],
        "mcp_tool": "depmap_synthetic_lethal_evidence",
        "lineage_mcp_tool": "depmap_lineage_mutation_dependency",
    },
    {
        "intent": "dependency_to_mutation",
        "description": "Fix a CRISPR dependency target and find mutation events associated with it.",
        "required": ["target_gene"],
        "optional": ["lineage", "event", "source_gene", "limit"],
        "examples_zh": ["哪些突变会影响GPX4依赖", "固定TP53 dependency找突变"],
        "precise_prompt_template_zh": "在泛癌范围固定{target_gene} dependency，查询哪些{event}突变与其依赖变化相关。",
        "confusable_with": ["mutation_to_dependency"],
        "mcp_tool": "depmap_synthetic_lethal_evidence",
    },
    {
        "intent": "codependency_evidence",
        "description": "Rank precomputed positive or negative CRISPR Gene Effect co-dependency partners for one exact target gene, globally and optionally within one lineage.",
        "required": ["gene"],
        "optional": ["lineage", "direction", "limit"],
        "examples_zh": ["哪些基因和KRAS共依赖", "肺癌里谁与KRAS正共依赖"],
        "precise_prompt_template_zh": "查询{gene}的{direction}CRISPR Gene Effect共依赖伙伴；正共依赖不是合成致死。",
        "confusable_with": ["gene_pair_evidence", "true_love_gene_catalog"],
        "mcp_tool": "depmap_codependency_evidence",
        "inventory_patterns": ["*CRISPR基因-基因共依赖分析*"],
    },
    {
        "intent": "gene_pair_evidence",
        "description": "Compare coexpression, CRISPR codependency, and expression-to-dependency evidence for two genes.",
        "required": ["source_gene", "target_gene"],
        "optional": ["lineage"],
        "examples_zh": ["ESR1和FOXA1相关吗", "比较两个基因的表达相关和共依赖"],
        "precise_prompt_template_zh": "比较{source_gene}与{target_gene}的共表达、CRISPR共依赖和表达—依赖关联，并分别标明数据模态。",
        "confusable_with": [],
        "mcp_tool": "depmap_pair_evidence",
    },
    {
        "intent": "cancer_dependency_ranking",
        "description": "Rank genes selectively required by one cancer lineage.",
        "required": ["lineage"],
        "optional": ["gene", "ranking", "exclude_common_essential", "limit"],
        "examples_zh": ["肝癌最依赖哪些基因", "FBXO7在哪些癌种选择性必需"],
        "precise_prompt_template_zh": "查询{lineage}中{gene}的选择性依赖，或返回Top {limit}；精确基因查询不得用Top-N缺席当阴性。",
        "confusable_with": ["mutation_anchor_discovery"],
        "mcp_tool": "depmap_lineage_dependencies",
        "inventory_patterns": ["*lineage_dependency_tests*"],
    },
    {
        "intent": "model_gene_effect_slice",
        "description": "Return bounded ModelID-keyed Chronos Gene Effect rows for one exact gene.",
        "required": ["gene"],
        "optional": ["lineage", "model_id", "gene_effect_at_or_below", "limit"],
        "examples_zh": ["哪些模型依赖GPX4", "髓系模型中TP53的Gene Effect"],
        "precise_prompt_template_zh": "按canonical ModelID查询{gene}的逐模型Chronos Gene Effect。",
        "confusable_with": ["cancer_dependency_ranking"],
        "mcp_tool": "depmap_model_gene_effect",
    },
    {
        "intent": "cross_platform_dependency_validation",
        "description": "Read completed Broad Chronos versus Sanger CRISPR and DEMETER2 RNAi validation for one exact gene.",
        "required": ["gene"],
        "optional": ["scope", "lineage"],
        "examples_zh": ["这个基因的依赖在RNAi中能复现吗", "检查Sanger CRISPR一致性"],
        "precise_prompt_template_zh": "查询{gene}在CRISPR、Sanger与RNAi平台间的预计算验证。",
        "confusable_with": ["gene_pair_evidence", "pan_cancer_dependency_summary"],
        "mcp_tool": "depmap_cross_platform_validation",
    },
    {
        "intent": "pan_cancer_dependency_summary",
        "description": "Summarize bounded precomputed lineage dependency rankings across every completed cancer lineage in one request.",
        "required": [],
        "optional": ["gene", "ranking", "exclude_common_essential", "limit"],
        "examples_zh": ["概览所有癌种的依赖基因", "FBXO7对哪些肿瘤影响最大"],
        "precise_prompt_template_zh": "若指定{gene}则对每个已完成癌种返回 FOUND/NOT_RETAINED/NOT_TESTED；否则每个癌种返回Top {limit}。",
        "confusable_with": ["cancer_dependency_ranking"],
        "mcp_tool": "depmap_pan_cancer_dependencies",
        "inventory_patterns": ["*lineage_dependency_tests*"],
    },
    {
        "intent": "tf_activity_to_dependency",
        "description": "Fix an inferred transcription-factor activity and query associated CRISPR Gene Effect targets.",
        "required": [],
        "optional": ["transcription_factor", "target_gene", "limit", "view"],
        "examples_zh": ["STAT3活性和哪些基因依赖相关", "列出已安装的TF活性宇宙", "查ESR1 TF活性与GPX4依赖"],
        "precise_prompt_template_zh": "查询冻结TF宇宙或{transcription_factor}活性与CRISPR Gene Effect；不得用浏览器重建DoRothEA。",
        "confusable_with": ["gene_pair_evidence"],
        "mcp_tool": "depmap_tf_dependency_evidence",
        "inventory_patterns": ["*转录因子活性*"],
    },
    {
        "intent": "expression_biomarker_model",
        "description": "Check whether a fixed CRISPR dependency target is eligible for expression-based LASSO/random-forest modeling and whether a validated cached model already exists.",
        "required": ["target_gene"],
        "optional": [],
        "examples_zh": ["为GPX4建立表达biomarker模型", "ESR1依赖能不能用表达预测", "查询WRN的LASSO模型资格"],
        "precise_prompt_template_zh": "查询{target_gene}依赖靶点的表达biomarker建模资格与已有缓存；若尚未建模，说明按需执行入口。",
        "confusable_with": ["gene_pair_evidence", "tf_activity_to_dependency"],
        "mcp_tool": "depmap_biomarker_model_evidence",
        "inventory_patterns": ["*表达基因-CRISPR基因依赖相关性分析*"],
    },
    {
        "intent": "true_love_gene_catalog",
        "description": "Query TLG catalogs by explicit scope: pancancer rank-1/derived tables, or lineage-scoped TLG when that table exists.",
        "required": ["catalog"],
        "optional": ["gene", "partner", "limit", "scope", "lineage"],
        "conditional_optional": {
            "coverage": {
                "when_catalog_in": [
                    "negative_r_lt_minus_0_3",
                    "positive_reciprocal_top20",
                ]
            }
        },
        "limit_max": 100,
        "examples_zh": ["查询真爱基因", "找r小于-0.3的负共依赖候选", "查询正相关互惠Top20"],
        "precise_prompt_template_zh": "查询26Q1的{catalog}真爱基因目录，可选{coverage}覆盖层，并说明相关性不能证明合成致死。",
        "confusable_with": ["gene_pair_evidence"],
        "mcp_tool": "depmap_true_love_evidence",
        "inventory_patterns": ["*CRISPR基因-基因共依赖分析*"],
    },
    {
        "intent": "gene_evidence",
        "description": "Retrieve available precomputed pathway or regulator enrichment evidence.",
        "required": ["gene"],
        "optional": ["lineage", "collection", "limit"],
        "examples_zh": ["这些候选富集到什么通路", "做Reactome富集"],
        "precise_prompt_template_zh": "查询{gene}的预计算通路与调控因子富集证据，并说明集合与统计口径。",
        "confusable_with": [],
        "mcp_tool": "depmap_gene_evidence",
    },
    {
        "intent": "tcga_expression_survival",
        "description": "Query TCGA tumor expression and OS/DSS/DFI/PFI association for one gene.",
        "required": ["gene"], "optional": ["project", "lineage", "endpoint", "limit"],
        "examples_zh": ["ESR1在TCGA乳腺癌中的表达和生存关系", "查询TP53的DSS"],
        "precise_prompt_template_zh": "查询{gene}的TCGA {endpoint}表达生存证据。",
        "confusable_with": ["gene_evidence"], "mcp_tool": "tcga_gene_expression_survival",
    },
    {
        "intent": "drug_gene_evidence",
        "description": "Query a precomputed PRISM drug-gene association globally or in one lineage.",
        "required": ["drug", "gene"], "optional": ["lineage", "limit"],
        "examples_zh": ["奥拉帕利和BRCA1有什么药物关联", "肺癌中这个药对EGFR的结果"],
        "precise_prompt_template_zh": "查询{drug}与{gene}的PRISM证据。",
        "confusable_with": ["gene_evidence"], "mcp_tool": "depmap_drug_evidence",
    },
    {
        "intent": "subtype_evidence",
        "description": "List eligible molecular-subtype contrasts or query subtype-specific dependency rows.",
        "required": [], "optional": ["gene", "lineage", "contrast_id", "limit"],
        "examples_zh": ["有哪些分子亚型分析", "乳腺癌亚型中ESR1依赖如何"],
        "precise_prompt_template_zh": "查询{lineage}的{contrast_id}亚型依赖证据。",
        "confusable_with": ["cancer_dependency_ranking"], "mcp_tool": "depmap_subtype_evidence",
        "inventory_patterns": ["*subtype_dependency*"],
    },
    {
        "intent": "coamplification_evidence",
        "description": "Query source-partner co-amplification and retained target-dependency evidence.",
        "required": ["source_gene"], "optional": ["partner_gene", "target_gene", "layer", "limit"],
        "examples_zh": ["CTTN和RNF121共扩增后依赖什么", "查询两个基因共扩增"],
        "precise_prompt_template_zh": "查询{source_gene}与{partner_gene}共扩增及{target_gene}依赖证据。",
        "confusable_with": ["gene_pair_evidence"], "mcp_tool": "depmap_coamplification_evidence",
        "inventory_patterns": ["*coamplification_dependency*"],
    },
    {
        "intent": "three_d_evidence",
        "description": "Query one completed 3D-screen evidence family with its required cohort or gene entities.",
        "required": ["family"], "optional": ["gene", "source_gene", "target_gene", "cohort", "contrast", "omic", "limit"],
        "examples_zh": ["查询3D培养中的依赖基因", "比较3D和2D的依赖差异"],
        "precise_prompt_template_zh": "查询3D模块{family}的预计算证据。",
        "confusable_with": ["gene_pair_evidence"], "mcp_tool": "depmap_3d_evidence",
        "inventory_patterns": ["depmap-26q1-3d"],
    },
)
