#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(data.table);library(jsonlite)})
args<-commandArgs(trailingOnly=TRUE);arg<-function(name,default=NULL){x<-grep(paste0('^--',name,'='),args,value=TRUE);if(!length(x))default else sub(paste0('^--',name,'='),'',x[[1]])}
data_root<-normalizePath(arg('data-root'),mustWork=TRUE);knowledge_root<-normalizePath(arg('knowledge-root'),mustWork=TRUE);root<-file.path(knowledge_root,'depmap-26q1-3d');out<-file.path(root,'integrated_validation');dir.create(out,recursive=TRUE,showWarnings=FALSE)
canon<-function(a,b)ifelse(a<=b,paste(a,b,sep='::'),paste(b,a,sep='::'))
stable<-fread(file.path(root,'true_love_stability','all_3d_lineage_adjusted','stable_true_love_pairs.csv.gz'));stable[,pair_key:=canon(gene_a,gene_b)]
two_d_path<-file.path(knowledge_root,'depmap-26q1-full','true_love_gene','high_confidence_stability','final_high_confidence_true_love_genes.csv.gz');two<-fread(two_d_path);two[,pair_key:=canon(gene_a,gene_b)];stable[,present_in_stable_2d:=pair_key%chin%two$pair_key]
fwrite(stable,file.path(out,'true_love_2d_3d_validation.csv.gz'),compress='gzip')
sets<-fread(file.path(data_root,'geneset_table_updated.csv'));sets[,GeneSymbol:=toupper(GeneSymbol)];universe<-unique(sets$GeneSymbol);query<-intersect(unique(c(stable$gene_a,stable$gene_b)),universe);enrich<-sets[,.(set_genes=list(unique(GeneSymbol))),by=.(Geneset,Source)];enrich[,`:=`(set_size=lengths(set_genes),overlap_n=vapply(set_genes,function(z)sum(z%chin%query),integer(1)))];enrich[,p_value:=vapply(seq_len(.N),function(i)phyper(overlap_n[i]-1,set_size[i],length(universe)-set_size[i],length(query),lower.tail=FALSE),numeric(1))];enrich[,fdr:=p.adjust(p_value,'BH')];enrich[,overlap_genes:=vapply(set_genes,function(z)paste(intersect(z,query),collapse=';'),character(1))];enrich[,set_genes:=NULL];setorder(enrich,fdr,-overlap_n);fwrite(enrich,file.path(out,'stable_true_love_geneset_enrichment.csv'))
mods<-c('expression_dependency','cnv_dependency','damaging_dependency','hotspot_dependency');evidence<-list()
for(m in mods){p<-file.path(root,'omics_dependency',m,'significant_associations.csv.gz');x<-fread(p);if(nrow(x)){x[,modality:=m];x[,feature:=feature_gene];x[,target:=target_gene];evidence[[m]]<-x[,.(modality,feature,target)]}}
cp<-file.path(root,'coamplification_dependency','significant_global_fdr.csv.gz');if(file.exists(cp)){x<-fread(cp);if(nrow(x))evidence[['coamplification']]<-x[,.(modality='coamplification',feature=paste(gene_a,gene_b,sep='::'),target=target_gene)]}
ev<-rbindlist(evidence,fill=TRUE);if(nrow(ev)){summary<-ev[,.(evidence_count=.N,evidence_families=uniqueN(modality),modalities=paste(sort(unique(modality)),collapse=';'),features=paste(head(unique(feature),20),collapse=';')),by=target][order(-evidence_families,-evidence_count)];fwrite(ev,file.path(out,'integrated_evidence_long.csv.gz'),compress='gzip');fwrite(summary,file.path(out,'integrated_target_candidates.csv.gz'),compress='gzip')}else summary<-data.table()
manifest<-list(schema_version=1,family='3d_integrated_validation',status='complete',qa_status='PASS',stable_3d_true_love_pair_count=nrow(stable),stable_2d_overlap_count=stable[present_in_stable_2d==TRUE,.N],stable_2d_overlap_fraction=stable[,mean(present_in_stable_2d)],significant_geneset_count=enrich[fdr<=.05,.N],integrated_target_count=nrow(summary),interpretation='2D overlap and geneset enrichment are validation layers; integrated evidence counts do not combine p-values and do not establish causality');write_json(manifest,file.path(out,'manifest.json'),auto_unbox=TRUE,pretty=TRUE)
