#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(data.table);library(jsonlite);library(limma)})
args<-commandArgs(trailingOnly=TRUE);arg<-function(name,default=NULL){x<-grep(paste0('^--',name,'='),args,value=TRUE);if(!length(x))default else sub(paste0('^--',name,'='),'',x[[1]])}
data_root<-normalizePath(arg('data-root'),mustWork=TRUE);knowledge_root<-normalizePath(arg('knowledge-root'),mustWork=TRUE);amp_threshold<-as.numeric(arg('amp-threshold','2'));min_group_n<-as.integer(arg('min-group-n','8'))
out<-file.path(knowledge_root,'depmap-26q1-3d','coamplification_dependency');dir.create(out,recursive=TRUE,showWarnings=FALSE);checkpoint<-file.path(out,'pair_checkpoints');dir.create(checkpoint,showWarnings=FALSE)
meta<-fread(file.path(data_root,'screen_metadata.csv'))[PassesQC==TRUE&ScreenType%chin%c('3DO','3DN')]
read_mat<-function(file,id_col='ModelID'){x<-fread(file,check.names=FALSE);ids<-x[[1]];x[[1]]<-NULL;g<-toupper(sub(' \\([^()]++\\)$','',names(x),perl=TRUE));m<-as.matrix(x);storage.mode(m)<-'double';rownames(m)<-ids;colnames(m)<-g;list(m=m,g=g)}
cn<-read_mat(file.path(data_root,'next_gen_copy_number.csv'));cm<-cn$m[match(meta$ModelID,rownames(cn$m)),,drop=FALSE];amp<-is.finite(cm)&cm>=amp_threshold;prev<-colSums(amp);eligible<-which(prev>=min_group_n&prev<=nrow(amp)-min_group_n)
z<-crossprod(amp[,eligible,drop=FALSE]*1);p<-prev[eligible];so<-outer(p,rep(1,length(p)))-z;po<-t(so);keep<-which(upper.tri(z)&z>=min_group_n&so>=min_group_n&po>=min_group_n,arr.ind=TRUE)
pairs<-data.table(pair_id=sprintf('pair_%04d',seq_len(nrow(keep))),gene_a=cn$g[eligible[keep[,1]]],gene_b=cn$g[eligible[keep[,2]]],coamp_n=z[keep],a_only_n=so[keep],b_only_n=po[keep])
eff<-read_mat(file.path(data_root,'screen_gene_effect.csv'));em<-eff$m[match(meta$ScreenID,rownames(eff$m)),,drop=FALSE];complete<-colSums(is.finite(em))==nrow(em);em<-em[,complete,drop=FALSE];targets<-eff$g[complete]
for(i in seq_len(nrow(pairs))){path<-file.path(checkpoint,paste0(pairs$pair_id[i],'.csv.gz'));if(file.exists(path))next;ia<-match(pairs$gene_a[i],cn$g);ib<-match(pairs$gene_b[i],cn$g);grp<-fcase(amp[,ia]&amp[,ib],'coamp',amp[,ia]&!amp[,ib],'a_only',!amp[,ia]&amp[,ib],'b_only',default='neither');sel<-grp%chin%c('coamp','a_only','b_only');d<-data.frame(group=factor(grp[sel],levels=c('a_only','b_only','coamp')),lineage=factor(meta$OncotreeLineage[sel]));design<-model.matrix(~group+lineage,d);fit0<-lmFit(t(em[sel,,drop=FALSE]),design);contrast<-makeContrasts(coamp_vs_a_only=groupcoamp,coamp_vs_b_only=groupcoamp-groupb_only,levels=design);fit<-eBayes(contrasts.fit(fit0,contrast));rows<-list();for(direction in colnames(contrast)){tt<-topTable(fit,coef=direction,number=Inf,sort.by='none');rows[[direction]]<-data.table(pair_id=pairs$pair_id[i],gene_a=pairs$gene_a[i],gene_b=pairs$gene_b[i],contrast=direction,target_gene=targets,effect_difference=tt$logFC,p_value=tt$P.Value,fdr_within_pair=p.adjust(tt$P.Value,'BH'))};res<-rbindlist(rows);fwrite(res,path,compress='gzip');if(i%%5L==0L||i==nrow(pairs))message(i,'/',nrow(pairs))}
all<-rbindlist(lapply(pairs$pair_id,function(id)fread(file.path(checkpoint,paste0(id,'.csv.gz')))));all[,fdr_global:=p.adjust(p_value,'BH')];hits<-all[effect_difference<0&fdr_within_pair<=.05];global_hits<-all[effect_difference<0&fdr_global<=.05]
fwrite(pairs,file.path(out,'eligible_pairs.csv'));fwrite(hits,file.path(out,'significant_within_pair.csv.gz'),compress='gzip');fwrite(global_hits,file.path(out,'significant_global_fdr.csv.gz'),compress='gzip')
manifest<-list(schema_version=1,family='3d_coamplification_dependency',status='complete',qa_status='PASS',model_count=nrow(meta),amp_threshold=amp_threshold,min_group_n=min_group_n,eligible_gene_count=length(eligible),eligible_pair_count=nrow(pairs),target_count=length(targets),nominal_test_count=nrow(all),within_pair_hit_count=nrow(hits),global_fdr_hit_count=nrow(global_hits),method='lineage-adjusted limma; co-amplified versus source-only; BH reported both within pair and globally',interpretation='observational conditional dependency; not causal synthetic lethality');write_json(manifest,file.path(out,'manifest.json'),auto_unbox=TRUE,pretty=TRUE)
