#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(data.table);library(jsonlite);library(fgsea)})
args<-commandArgs(trailingOnly=TRUE);arg<-function(name,default=NULL){x<-grep(paste0("^--",name,"="),args,value=TRUE);if(!length(x))default else sub(paste0("^--",name,"="),"",x[[1]])}
data_root<-normalizePath(arg("data-root"),mustWork=TRUE);knowledge_root<-normalizePath(arg("knowledge-root"),mustWork=TRUE);min_n<-as.integer(arg("min-lineage-n","5"));fdr_max<-as.numeric(arg("fdr-max","0.05"))
out_root<-file.path(knowledge_root,"depmap-26q1-3d","lineage_dependency_enrichment");dir.create(out_root,recursive=TRUE,showWarnings=FALSE)
meta<-fread(file.path(data_root,"screen_metadata.csv"))[PassesQC==TRUE&ScreenType%chin%c("3DO","3DN")]
x<-fread(file.path(data_root,"screen_gene_effect.csv"),check.names=FALSE);ids<-x[[1]];x[[1]]<-NULL;genes<-toupper(sub(" \\([^()]++\\)$","",names(x),perl=TRUE));effect<-as.matrix(x);storage.mode(effect)<-"double";rownames(effect)<-ids;colnames(effect)<-genes;meta<-meta[match(rownames(effect),ScreenID)];rm(x)
gs<-fread(file.path(data_root,"geneset_table_updated.csv"),header=TRUE);if(names(gs)[[1]]=="")gs[[1]]<-NULL;gs<-gs[!is.na(Geneset)&!is.na(GeneSymbol)];pathways<-split(toupper(gs$GeneSymbol),paste(gs$Source,gs$Geneset,sep="::"));pathways<-lapply(pathways,unique)
groups<-list(all_3d=which(meta$ScreenType%chin%c("3DO","3DN")),organoid_3do=which(meta$ScreenType=="3DO"),cns_3dn=which(meta$ScreenType=="3DN"));lc<-meta[, .N,by=OncotreeLineage][N>=min_n]
for(i in seq_len(nrow(lc)))groups[[paste0("lineage__",gsub("[^A-Za-z0-9]+","_",tolower(lc$OncotreeLineage[[i]])))]]<-which(meta$OncotreeLineage==lc$OncotreeLineage[[i]])
catalog<-list()
for(key in names(groups)){idx<-groups[[key]];score<--colMeans(effect[idx,,drop=FALSE],na.rm=TRUE);names(score)<-genes;score<-sort(score[is.finite(score)],decreasing=TRUE);res<-as.data.table(fgseaMultilevel(pathways=pathways,stats=score,minSize=15,maxSize=500,eps=0));res[,`:=`(group=key,screen_n=length(idx),passes_fdr=!is.na(padj)&padj<=fdr_max,abs_NES=abs(NES))];setorder(res,padj,-abs_NES);res[,abs_NES:=NULL];root<-file.path(out_root,key);dir.create(root,recursive=TRUE,showWarnings=FALSE);fwrite(res,file.path(root,"enrichment.csv.gz"),compress="gzip");fwrite(res[passes_fdr==TRUE],file.path(root,"significant_enrichment.csv.gz"),compress="gzip");manifest<-list(schema_version=1,release="NextGen Model Manuscript 2026",family="3d_lineage_dependency_enrichment",group=key,status="complete",screen_n=length(idx),tested_pathway_count=nrow(res),significant_pathway_count=res[passes_fdr==TRUE,.N],method="fgseaMultilevel on negative mean Gene Effect ranks");write_json(manifest,file.path(root,"manifest.json"),auto_unbox=TRUE,pretty=TRUE);catalog[[key]]<-as.data.table(manifest)[,.(group,screen_n,tested_pathway_count,significant_pathway_count,status)]}
catalog<-rbindlist(catalog);fwrite(catalog,file.path(out_root,"group_catalog.csv"));write_json(list(schema_version=1,release="NextGen Model Manuscript 2026",family="3d_lineage_dependency_enrichment",status="complete",group_count=nrow(catalog),min_lineage_n=min_n),file.path(out_root,"manifest.json"),auto_unbox=TRUE,pretty=TRUE)
